---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-server-sources
  namespace: side-projects
spec:
  storageClassName: nfs-source-http-server
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 5Gi
  selector:
    matchLabels:
      sources: http-server
      volume-type: nfs
