---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: http-server-sources
  labels:
    sources: http-server
    volume-type: nfs
spec:
  storageClassName: nfs-source-http-server
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: $HOST_IP
    path: '$PROJECT_PATH'
  persistentVolumeReclaimPolicy: Retain
