---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tmp-pv-claim
  namespace: side-projects
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
