apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: side-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: postgres
  template:
    metadata:
      labels:
        app: postgres
        role: postgres
    spec:
      containers:
      - name: postgres
        image:  postgres:lastest
        ports:
        - name: postgres-port
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data/
        env:
        - name: POSTGRES_DB
          value: notifications_db
        - name: POSTGRES_USER
          value: notifications_user
        - name: POSTGRES_PASSWORD
          value: notifications_password
      volumes:
      - name: data
        hostPath:
          path: /data/pg/notifications
